version: "3"

services:
  spotter-exercise-backend:
    image: ${CONTAINER_REGISTRY}/spotter-exercise:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
    env_file:
      - ./.env
    command: node index.js
  spotterdb:
    image: postgres:15.1-alpine
    container_name: spotterdb
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  dbdata:
    driver: local
